using SamplePhoneApp;
namespace MoqaLate.Autogenerated
{
public partial class NavigatorMoqaLate : INavigator
{
// ------------ Property CurrentUri
private string _CurrentUri;
public virtual string CurrentUri
{
get { return _CurrentUri; }
}
public virtual void __SetCurrentUri(string val)
{
   _CurrentUri = val;
}
// ------------ Property CheckUriBeforeNavigating
private bool _CheckUriBeforeNavigating;
public virtual bool CheckUriBeforeNavigating
{
get { return _CheckUriBeforeNavigating; }
set { _CheckUriBeforeNavigating = value; }
}
public virtual void __SetCheckUriBeforeNavigating(bool val)
{
   _CheckUriBeforeNavigating = val;
}
}
}
